### ISSUE TITLE
Capacitacion del Ing. Huerta

### ISSUE THREAD

**Issue by Pablini** [Pablini/CCGLOBAL#3]
Capacitacion completa del sistema LEARN Manager para el Ing. Huerta

**Comment by Pablini** [comment]
@EugeLugo21 no se te vaya  a olvider el proyector

**Comment by icastellanos** [comment]
Encontré estas 2 placas son de la esquina de la secretaria

    Placa       Fecha      Hora        Fecha_2     Hora_2
ULR6390: 01-24-17, 07:41:14 - 01-31-17, 16:25:06
HCC5396: 01-24-17, 07:41:14 - 01-31-17, 16:25:08

**Comment by Pablini** [comment]
finish
